/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asdf_opencvdemo_OpenCVHelper */

#ifndef _Included_com_asdf_opencvdemo_OpenCVHelper
#define _Included_com_asdf_opencvdemo_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_asdf_opencvdemo_OpenCVHelper
 * Method:    toGray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_asdf_opencvdemo_OpenCVHelper_toGray
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
