/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asdf_utils_OpenCVJniHelper */

#ifndef _Included_com_asdf_utils_OpenCVJniHelper
#define _Included_com_asdf_utils_OpenCVJniHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_asdf_utils_OpenCVJniHelper
 * Method:    jni_toGray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_asdf_utils_OpenCVJniHelper_jni_1toGray
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
